// <auto-generated />
using System;
using AppResenas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppResenas.Migrations
{
    [DbContext(typeof(ResenasDataBaseContext))]
    partial class ResenasDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppResenas.Models.Autor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("AppResenas.Models.Libro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<int?>("autorid")
                        .HasColumnType("int");

                    b.Property<string>("isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("resenaid")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.HasIndex("autorid");

                    b.HasIndex("resenaid");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("AppResenas.Models.Resena", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<double>("puntajeAcum")
                        .HasColumnType("float");

                    b.Property<string>("texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("votos")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Usuarioid");

                    b.ToTable("resenas");
                });

            modelBuilder.Entity("AppResenas.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<bool>("esAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("AppResenas.Models.Autor", b =>
                {
                    b.HasOne("AppResenas.Models.Usuario", null)
                        .WithMany("autoresFavoritos")
                        .HasForeignKey("Usuarioid");
                });

            modelBuilder.Entity("AppResenas.Models.Libro", b =>
                {
                    b.HasOne("AppResenas.Models.Usuario", null)
                        .WithMany("librosFavoritos")
                        .HasForeignKey("Usuarioid");

                    b.HasOne("AppResenas.Models.Autor", "autor")
                        .WithMany("libros")
                        .HasForeignKey("autorid");

                    b.HasOne("AppResenas.Models.Resena", "resena")
                        .WithMany()
                        .HasForeignKey("resenaid");
                });

            modelBuilder.Entity("AppResenas.Models.Resena", b =>
                {
                    b.HasOne("AppResenas.Models.Usuario", null)
                        .WithMany("resenasFavoritas")
                        .HasForeignKey("Usuarioid");
                });
#pragma warning restore 612, 618
        }
    }
}
